### ISSUE TITLE
videogular2 Cannot find name 'AudioTrackList'. && 'VideoTrackList'

### ISSUE THREAD

**Issue by khallad2** [videogular/ngx-videogular#17]
### Description
using Angular-8
"@angular/animations": "8.x.x",
"@angular/common": "8.x.x",
"@angular/compiler": "8.x.x",
"@angular/core": "8.x.x",
trying to build the app but i get the following errors.

### Expected Behavior
it should be built and run normally

### Actual Behavior
[at-loader] Checking finished with 4 errors chunk {0} vendor.js (vendor) 4.06 MB {2} [initial] [rendered]
chunk {1} app.js, app.css (app) 3.63 MB {0} [initial] [rendered]
chunk {2} polyfills.js (polyfills) 695 kB [entry] [rendered]

ERROR in [at-loader] ./node_modules/videogular2/src/core/vg-media/i-media-element.d.ts:17:27
TS2304: Cannot find name 'AudioTrackList'.

ERROR in [at-loader] ./node_modules/videogular2/src/core/vg-media/i-media-element.d.ts:135:27
TS2304: Cannot find name 'VideoTrackList'.

ERROR in [at-loader] ./node_modules/videogular2/src/core/vg-media/vg-media-element.d.ts:5:27
TS2304: Cannot find name 'AudioTrackList'.

ERROR in [at-loader] ./node_modules/videogular2/src/core/vg-media/vg-media-element.d.ts:42:18
TS2304: Cannot find name 'VideoTrackList'.
webpack: Failed to compile.

### Steps to Reproduce
 Step 1: npm install
 Step 2: npm start

[Videogular2 error.txt](https://github.com/videogular/ngx-videogular/files/4937946/Videogular2.error.txt)

please support or tell us if it is not possible to can look for alternatives..

i am posting here for Videogoular2 according your post on Videogoular2/issues
![Screenshot 2020-07-17 at 15 06 50](https://user-images.githubusercontent.com/32259466/87789334-2c4d9c00-c83f-11ea-8c8e-cf6801dc52c4.png)

**Comment by IxquitilisSaid** [comment]
Hey, thanks for taking an interest in our project! 
So, from the errorlog you sent, that's the `videogular2`, this is ngx-videogular.

The missing typings were fixed here before the release.
Try installing us `npm i @videogular/ngx-videogular` and changing your import paths (the module names are the same ;)) 
Can guarantee those errors are solved and you get a 48% smaller bundle size with the exact same functionalities you know, trust and love from videogular2!

Let me know if you need help with anything else and I'll be sure to answer expeditiously (office day today)

**Comment by lashisu** [comment]
**Issue still there even with ngx-videogular**

### I am importing like below.

`import { VgCoreModule, VgControlsModule, VgOverlayPlayModule, VgBufferingModule, VgStreamingModule } from 'ngx-videogular';`

### What are the issues?

![image](https://user-images.githubusercontent.com/1376383/87957335-c0cd2e00-cacd-11ea-8813-ce2f00bacf49.png)

**Comment by shanehsu** [comment]
See my response in #18, I think it should help.

**Comment by IxquitilisSaid** [comment]
@lashisu you installed the wrong project...
Like I said above, `@videogular/ngx-videogular` (the scope is important, else you're downloading some other lib with the same name)

**Comment by lashisu** [comment]
I corrected it t0 `@videogular/ngx-videogular` no. But getting below error now.

![image](https://user-images.githubusercontent.com/1376383/88019401-5b1d8800-cb47-11ea-9a77-025a27b68762.png)

**Comment by IxquitilisSaid** [comment]
Please read https://github.com/videogular/ngx-videogular/blob/master/docs/ngx-videogular-demo/SUMMARY.md

I removed the index barreling so you need to import each module from their own entry, for example:

```
import {CoreModule} from '@videogular/ngx-videogular/core';
import {ControlsModule} from '@videogular/ngx-videogular/controls';
import {BufferingModule} from '@videogular/ngx-videogular/buffering';
import {StreamingModule} from '@videogular/ngx-videogular/streaming';
import {OverlayPlayModule} from '@videogular/ngx-videogular/overlay-play';
```

**Comment by lashisu** [comment]
### Suggested Module worked with `Vg` like below:-

```
import { VgCoreModule } from '@videogular/ngx-videogular/core';
import { VgControlsModule } from '@videogular/ngx-videogular/controls';
import { VgBufferingModule } from '@videogular/ngx-videogular/buffering';
import { VgStreamingModule } from '@videogular/ngx-videogular/streaming';
import { VgOverlayPlayModule } from '@videogular/ngx-videogular/overlay-play';
```

### Now, Getting error for below:-

```
import { BitrateOption, VgAPI } from '@videogular/ngx-videogular';
import { VgHLS } from '@videogular/ngx-videogular';
```

**Seems that missing correct import. Please suggest**

**Comment by IxquitilisSaid** [comment]
Please check the edit to my last comment.

But fixing your imports:

```
import {
  BitrateOptions,
  VgApiService,
} from '@videogular/ngx-videogular/core';
import { VgHlsDirective } from '@videogular/ngx-videogular/streaming';
```

**Comment by khallad2** [comment]
> Hey, thanks for taking an interest in our project!
> So, from the errorlog you sent, that's the `videogular2`, this is ngx-videogular.
> 
> The missing typings were fixed here before the release.
> Try installing us `npm i @videogular/ngx-videogular` and changing your import paths (the module names are the same ;))
> Can guarantee those errors are solved and you get a 48% smaller bundle size with the exact same functionalities you know, trust and love from videogular2!
> 
> Let me know if you need help with anything else and I'll be sure to answer expeditiously (office day today)

Thanks a lot it is working for me, now I can build the project ;)

**Comment by IxquitilisSaid** [comment]
@khallad2 my pleasure! Glad that your issues are fixed 😄
